name: Security News Bot

on:
  schedule:
    - cron: '*/10 * * * *'  # ✅ 5分ごとに実行（UTC基準）
  workflow_dispatch:  # ✅ 手動実行を可能にする

jobs:
  post_news:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests google-generativeai tweepy

      - name: Run script (scheduled or test mode)
        run: |
          if [ "${{ github.event_name }}" = "schedule" ]; then
            python security_news_bot.py
          else
            python security_news_bot.py --test
          fi
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          GOOGLE_SEARCH_API_KEY: ${{ secrets.GOOGLE_SEARCH_API_KEY }}
          GOOGLE_SEARCH_CX: ${{ secrets.GOOGLE_SEARCH_CX }}
          X_API_KEY: ${{ secrets.X_API_KEY }}
          X_API_SECRET: ${{ secrets.X_API_SECRET }}
          X_ACCESS_TOKEN: ${{ secrets.X_ACCESS_TOKEN }}
          X_ACCESS_TOKEN_SECRET: ${{ secrets.X_ACCESS_TOKEN_SECRET }}
