name: Test Gemini Models

on: workflow_dispatch  # 手動で実行可能にする

jobs:
  test_models:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10

      - name: Install dependencies
        run: pip install google-generativeai

      - name: Run test script
        run: python test_gemini.py  # ← test_gemini.py をルートディレクトリで実行
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
