name: Test Google Search API

on:
  workflow_dispatch:  # 手動実行用

jobs:
  test_google_search:
    runs-on: ubuntu-latest

    steps:
      - name: リポジトリをチェックアウト
        uses: actions/checkout@v3

      - name: Python をセットアップ
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: 依存関係をインストール
        run: pip install requests

      - name: Google Search API のテストを実行
        run: python test_google_search.py
        env:
          GOOGLE_SEARCH_API_KEY: ${{ secrets.GOOGLE_SEARCH_API_KEY }}
          GOOGLE_SEARCH_CX: ${{ secrets.GOOGLE_SEARCH_CX }}
